/*
openrpg - config.h
Created on: Dec 1, 2016

OpenRPG Software License - Version 1.0 - February 10th, 2017 <http://www.openrpg.io/about/license/>
This is free software: you are free to change and redistribute it.
here is NO WARRANTY, to the extent permitted by law.

--------------------------------------------------------------------------
This file is autogenerated from config.h.in 
during the cmake configuration of your project. If you need to make changes
edit the original config.h.in file NOT THIS FILE.
--------------------------------------------------------------------------
*/
#ifndef CONFIG_H_
#define CONFIG_H_

/* custom project wide defines */
#define VERSION_MAJOR 0
#define VERSION_MINOR 5
#define VERSION_TWEAK 0
#define VERSION_SUFFIX "dev"
#define VERSION "v0.5.0-dev"
#define AUTHOR "Nicholas Gaulke"
#define COPYRIGHT "(C) 2016-2019 Nicholas Gaulke"
#define ASSET_LOC "/home/variable/Documents/Programming/openrpg/data"
#define DEBUG

#endif  /* CONFIG_H_ */
