[package]
name = "openrpg-api"
version = "0.1.0"
authors = ["Michael AKA hurnhu  <hurnhu@protonmail.com>"]

[dependencies]
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = "0.3.0"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0.11"
